sudo: required
services:
  - docker

before_install:
  - docker build -t elefteri/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true elefteri/frontend npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-883336430990"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
